server:
  servlet:
    context-path: /api/bank
  port: 8081
spring:
  datasource:
    username: root
    password: bankpassword
    url: jdbc:postgresql://localhost:5432/bankBD
    initialization-mode: always
    hikari.connectionTimeout: 20000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update 
    generate-ddl: true
    show-sql: true
