default:
  image: "kaiwinter/docker-java8-maven"

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - "mvn verify"
  artifacts:
    paths:
      - bank/target/
      - client/target/
      - employee/target/
  only:
    - master
    - merge_requests

sonarcloud-check:
  stage: test
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  script:
    - mvn verify sonar:sonar -Dsonar.qualitygate.wait=true
  only:
    - master
    - merge_requests

integration-tests:
  stage: test
  services:
    - postgres:9.6.17
  
  variables:
    POSTGRES_DB: bankBD
    POSTGRES_USER: root
    POSTGRES_PASSWORD: bankpassword
    POSTGRES_HOST_AUTH_METHOD: trust
  
  script:
    - mvn spring-boot:run -pl bank -Drun.profiles=dev

docker-image:
  stage: deploy
  services: 
    - docker:dind
  image: docker
  script:
    - docker build -t loremipsumbank/server:latest -t loremipsumbank/server:${CI_PIPELINE_ID} .
    - docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    - docker push loremipsumbank/server:${CI_PIPELINE_ID}
    - docker push loremipsumbank/server:latest
  only:
    - master
