version: '3'

services:
  database:
    image: postgres:9.6.17
    environment:
      - POSTGRES_DB=bankBD
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=bankpassword
    ports:
      - "5432:5432"
  server:
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/bankBD
    image: loremipsumbank/server:latest
    depends_on:
      - database
    ports:
      - 8080:8081
    links:
      - database